# Generated by Django 6.1.1 on 2026-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField()),
                ('body', models.TextField()),
                ('author', models.CharField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
